training_parameters:
  # Choose the type of normalization to apply to the data
  norm_type:
    ctnorm_global: true
    ctnorm_relative: true
    read_depth: true

  # Choose the type of genes to include in the training
  gene_type:
    metabolic: true
    nonmetabolic: true
    random: true

  # Choose the types of cells to train on
  cell_type:
    macrophages: true
    lcam_hi: true
    lcam_lo: true
    lcam_both: true
    all_clusters: true
    has_10_in_50pct: true
    has_10_in_70pct: true

  # Set which models to train
  models:
    - name: "lasso"
      train: true
    - name: "elasticnet"
      train: true
    - name: "svmlinear"
      train: true
    - name: "svmrbf"
      train: true
    - name: "randomforest"
      train: true
    - name: "xgboost"
      train: true
    - name: "spls"
      train: true
    - name: "lightgbm"
      train: true
