training_parameters:
  # Options: "raw", "absolute", "relative", "all"
  dataset_type: "raw" 
  # Options: true or false
  include_gene_ablation: true 
  # Options: true or false
  include_cell_type_ablation: true 
